### ISSUE TITLE
no top level LICENSE file

### ISSUE THREAD

**Issue by MarkAtwood** [ros2/geometry2#101]
This repo does not have a top level LICENSE file.
The MIT license makes the most sense for a project like this.

**Comment by dirk-thomas** [comment]
Please provide a pull request to the upstream repository instead. Since this is only a fork we think adding the LICENSE file upstream makes more sense.

Also afaik the packages in this repo use the BSD license - so MIT doesn't sound right (please don't copy and paste the same issue text into various repositories without actually checking if they apply).
