### ISSUE TITLE
Provide euclidean distance using tf2_echo

### ISSUE THREAD

**Issue by agutenkunst** [ros2/geometry2#382]
#### Feature description
tf2_echo could also provide information about the distance between the frames (starting with euclidean?)
Now and then I stumpled upon the need to see the euclidean distance between two frames. 

Looking at https://answers.ros.org/question/61957/math-functions-for-geometry_msgs/ https://answers.ros.org/question/60658/calculate-difference-between-two-poses/ https://answers.ros.org/question/203270/how-do-i-get-the-distancies-between-frames-in-openni_tracker/ https://answers.ros.org/question/232310/distance-between-two-robots-in-gazebo/ this is a need many have.

#### Implementation considerations
Currently the usage is
```
tf2_echo source_frame target_frame [echo_rate]
```

##### Option 1
Allow enabling it via ros param
```
ros2 run tf2_ros tf2_echo --ros-args -p euclidean_distance:=True
```

##### Option 2 
```
usage: tf2_echo frame1 frame2 [-h] [-r N] [--euclidean-distance]

optional arguments:
  -h, --help            show this help message and exit
  -r N, --rate N        Publishing rate in Hz (default: 1)
  --euclidean-distance   Publishing the euclidean distance (default: False)
```
The would change the API and would require some docs/tutorials to be changed. But it could also be done with deprecation.
Not sure what to use for the arguments parsing. Seems to be done bare metal, probably a new dep on something like *Boost.Program_options*  is undesired. 

---
Happy to open a PR if the discussion favors a feature like this!

**Comment by tfoote** [comment]
I don't think that we should extend tf2_echo in this way. There's a lot of things like this that might be useful. However that functionality could also be written in a few lines of python. 

This is a simple tool and starting to add alternative options to reduce or produce derivative data doesn't add value to the existing tool. This seems like a very specific need. To be more generic you'd really want to also capture the angular delta too at least. 

I also think that extending tf2_echo is the wrong way to approach this. Already there's a large fraction of the program dedicated to the command line parsing. And we have just spent a lot of energy removing boost from our dependency trees so adding that back is a non-starter. 

To this end I'd also strongly suggest just doing this in python. tf2_echo is only in c++ because it predated the python bindings. This can be written more compactly in python with simpler built in command line parsing. And for the dedicated purpose it can be a standalone script focused on the specific use case, which after being mature could be contributed to the tf2_tools package next to view_frames.py. 

There are many areas that can be improved by focusing on the use case and starting with a fresh plate to facilitate better pipelining with bash pipes or likely also some forms of fancier UI potentially could also be explored if the target is better human observation/understanding for example, people can't read scrolling data well.
