### ISSUE TITLE
tf2_echo reverse output

### ISSUE THREAD

**Issue by AlexeyMerzlyakov** [ros2/geometry2#470]
Hi,

I've found that `tf2_echo` command gives reversed from the `lookupTrasfrom()` transformation, if using the given in help message signature:
```
$ ros2 run tf2_ros tf2_echo source_frame target_frame
```

In the example I am using:
```
transform = tf_buffer>lookupTransform(to_frame_id, from_frame_id, cpp_ros_time, transform_timeout);
...
RCLCPP_INFO(get_logger(), "transform from %s -> to %s: %f, %f, %f",
  from_frame_id.c_str(), to_frame_id.c_str(),
  transform.value().transform.translation.x,
  transform.value().transform.translation.y,
  transform.value().transform.translation.z);
```
there is the following output:
```
transform from camera_left_frame -> to base_scan: 0.133000, -0.047000, -0.015000
```
while calling the `tf2_echo` from console gives:
```
$ ros2 run tf2_ros tf2_echo camera_left_frame base_scan
- Translation: [-0.133, 0.047, 0.015]
```

This looks like this appears because of following line in `tf2_echo.cpp`:
```
echo_transform = echoListener.buffer_.lookupTransform(
        source_frameid, target_frameid,
        tf2::TimePoint());
```

According to latest autodoc pages (https://docs.ros2.org/latest/api/tf2/classtf2_1_1BufferCore.html#a5d578ecbea2ec0fdb92de1616251e175), `lookupTransform()` routine takes `target_frame` first, and then `source_frame`.

Suggested change:
```
@@ -132,7 +132,7 @@ int main(int argc, char ** argv)
     try {
       geometry_msgs::msg::TransformStamped echo_transform;
       echo_transform = echoListener.buffer_.lookupTransform(
-        source_frameid, target_frameid,
+        target_frameid, source_frameid,
         tf2::TimePoint());
       std::cout.precision(3);
       std::cout.setf(std::ios::fixed, std::ios::floatfield);
```

**Comment by clalancette** [comment]
Yeah, I have to agree with you that this looks backwards.  But it has been like this for a *long* time (since at least https://github.com/ros2/geometry2/commit/591eb428364296fad71391bc6f117cdfc116e2bf), and it is consistent between the calls to [canTransform](https://github.com/ros2/geometry2/blob/16562cee8694c11f1f82b2bdbde2814fca1c7954/tf2_ros/src/tf2_echo.cpp#L120-L121) and [lookupTransform](https://github.com/ros2/geometry2/blob/16562cee8694c11f1f82b2bdbde2814fca1c7954/tf2_ros/src/tf2_echo.cpp#L134-L136), which leads me to believe this might be intentional.

@tfoote could you share any insights on this?

**Comment by aprotyas** [comment]
I had a confusion about the ordering of the arguments to `lookupTransform` as well, and this explanation may/may not be helpful:
https://github.com/ros2/geometry2/pull/452#issuecomment-914064884

**Comment by AlexeyMerzlyakov** [comment]
@clalancette, @aprotyas, thank you for the explanation! That indeed was my confusion: I initially thought that `tf2_echo` should return transformation (matrix) from source_frame -> to target_frame, while it is vice versa (it is actually coordinate of `target_frame's origin` in `source's_frame`). The comment from above helped me to get the understanding of what does it mean. Moreover, there is a note written in `tf2_echo` help message confirming that this is OK:
```
Note: This is the transform to get data from target_frame into the source_frame.
```
So, that is correct and made intentionally.

I've drawn the picture that did helped me and do hope will may be useful for anyone with the similar question:
![TF](https://user-images.githubusercontent.com/60094858/139281080-2afc9481-554b-4f1c-be76-a78e4d214a0a.png)

**Comment by tfoote** [comment]
Correct, this is one more duplicate of https://github.com/ros/geometry/issues/108 Thanks for the comprehensive diagram.

**Comment by mqnc** [comment]
I also got stuck on this for a long time. Also finding several posts on this where people noted that tf_echo is wrong because it flips the arguments in the lookup_transform call when actually lookup_transform is "wrong".

https://en.wikipedia.org/wiki/Active_and_passive_transformation <- this sheds some light on the issue.

Concerning this comment: https://github.com/ros2/geometry2/pull/452#issuecomment-914064884

Naming the frames target_frame and source_frame does not help if it does not clarify if you want to transform (move) points (or frames!) from a source_frame to a target_frame (as multiplication with a transformation matrix does in mathematics, consistent with tf_echo) or if you want to transform the reference frame of points from a source_frame to a target_frame, as lookup_transform assumes. Both transforms transform data. The fact that the call in tf_echo is effectively `lookup_transform(target_frame=source_frame, source_frame=target_frame, ...)` is clearly confusing and a sign of conflicting conventions.

In my opinion, naming them "parent"/"reference" and "child"/"local"/"dependent" is more clear and descriptive than "from"/"source" and "to"/"target".

Now that the naming is carved in stone however, I think there should at least be some remarks on this in the tutorials here
https://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28Python%29 and here https://wiki.ros.org/tf2/Tutorials/Time%20travel%20with%20tf2%20%28Python%29 where it is also just called "from" and "to". Maybe a link to the wikipedia article would also help.

I tried to do that but I can't sign up.
