### ISSUE TITLE
ModuleNotFoundError: No module named 'tf2_sensor_msgs'

### ISSUE THREAD

**Issue by YoushaaMurhij** [ros2/geometry2#471]
Is there any plan to include `tf2_sensor_msgs`?

**Comment by clalancette** [comment]
Eventually, yes.  But it is blocked by https://github.com/ros2/orocos_kinematics_dynamics/pull/19

**Comment by Flova** [comment]
Same with `tf2_geometry_msgs`.

**Comment by ozangungor12** [comment]
Sorry for the basic question, but I find it quite challenging to understand what is ported and what is not from ROS1 to ROS2.
Since I already see the `tf2_geometry_msgs` in this repo, I thought it was already available.
Also `sudo apt-get install ros-foxy-tf2-geometry-msgs` says that the package is already the newest version.
What is the easy way of understanding if a package in a repo is already ported or not? Is it the missing `setup.py` file?

**Comment by Flova** [comment]
The python part of the `tf2_geometry_msgs` was excluded by deleting its part from the `CMakeLists.txt` file, which disables the build of this part of the package. It is not very obvious that this part of the code is not being build. I agree with you. The code is already ported by deactivated due to an upstream dependency issue. This should be resolved by dropping the dependency as proposed in this PR #509.

**Comment by HenryPCardoso** [comment]
just use the command: 
sudo apt-get install ros-foxy-tf2-sensor-msgs
It worked fine for me

**Comment by Flova** [comment]
Imo. this issue can be closed as #509 is merged for a while now.

**Comment by Flova** [comment]
> just use the command: sudo apt-get install ros-foxy-tf2-sensor-msgs It worked fine for me

It could not be build due to a missing dependency prior to #509 iirc.. It was therefore no binary was released. 

Check your package.xml dependency definitions and run rosdep again if you need to install it explicitly like you did.

**Comment by clalancette** [comment]
Yes, this was long ago enabled, and is currently available in all of our supported distributions.  I'm going to close this one out.
